type Book @model {
  id: ID
  title: String
  Authors: [Author]
  Supplier :[Supplier]
}

type Author {
  id: ID
  first_name: String
  middle_name: String
  last_name: String
}

type Supplier {
  id: ID
  name: String
}
